package com.example.cashMap.models.enums;

public enum GoalModType {
    TITLE_MODIFICATION,
    DESCRIPTION_MODIFICATION,
    TARGET_VALUE_MODIFICATION,
    CURRENT_VALUE_MODIFICATION,
    DEADLINE_DATE_MODIFICATION,
    STATUS_MODIFICATION,
    CREATION,
    DELETION
}
